name: "Custom Bot Init"
description: "Initialize a GitHub App bot with proper git configuration"
author: "starburst997"

inputs:
  app-id:
    description: "GitHub App ID"
    required: false
  private-key:
    description: "GitHub App private key"
    required: false

outputs:
  token:
    description: "Generated GitHub App token"
    value: ${{ steps.generate-token.outputs.token }}
  name:
    description: "Configured git user name"
    value: ${{ steps.configure-git.outputs.name }}
  email:
    description: "Configured git user email"
    value: ${{ steps.configure-git.outputs.email }}

runs:
  using: "composite"
  steps:
    - name: Generate GitHub App token
      id: generate-token
      if: ${{ inputs.app-id != '' && inputs.private-key != '' }}
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
        owner: ${{ github.repository_owner }}

    - name: Configure git with GitHub App identity
      id: configure-git
      if: ${{ inputs.app-id != '' && inputs.private-key != '' }}
      shell: bash
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      run: |
        # Use the app-slug output from the create-github-app-token action
        APP_SLUG="${{ steps.generate-token.outputs.app-slug }}"

        # Set bot identity
        BOT_NAME="${APP_SLUG}[bot]"
        BOT_EMAIL="${{ inputs.app-id }}+${APP_SLUG}[bot]@users.noreply.github.com"

        # Configure git with the app's identity
        git config --global user.name "${BOT_NAME}"
        git config --global user.email "${BOT_EMAIL}"

        # Set outputs
        echo "name=${BOT_NAME}" >> $GITHUB_OUTPUT
        echo "email=${BOT_EMAIL}" >> $GITHUB_OUTPUT

        echo "✅ Configured git for bot: ${BOT_NAME}"
