name: Release

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize custom bot
        id: bot
        uses: ./
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_KEY }}

      - name: Clean workspace with git
        run: |
          git clean -fdx
          git reset --hard

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.bot.outputs.token }}

      - name: Version and Tag
        id: version
        uses: starburst997/auto-version@v1
        with:
          update-major-minor: true

      - name: Generate changelog and create release
        uses: starburst997/commits-logs@v1
        with:
          token: ${{ steps.bot.outputs.token }}
